//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP_Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PP_Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achternaam.
        /// </summary>
        internal static string Achternaam {
            get {
                return ResourceManager.GetString("Achternaam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begindatum.
        /// </summary>
        internal static string Begindatum {
            get {
                return ResourceManager.GetString("Begindatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschrijving.
        /// </summary>
        internal static string Beschrijving {
            get {
                return ResourceManager.GetString("Beschrijving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevestiging.
        /// </summary>
        internal static string Bevestiging {
            get {
                return ResourceManager.GetString("Bevestiging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einddatum.
        /// </summary>
        internal static string Einddatum {
            get {
                return ResourceManager.GetString("Einddatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve eerst een gebruiker te selecteren..
        /// </summary>
        internal static string FrmBeheerder_cmdGebruikerAanpassen_Click_Gelieve_eerst_een_gebruiker_te_selecteren_ {
            get {
                return ResourceManager.GetString("FrmBeheerder_cmdGebruikerAanpassen_Click_Gelieve_eerst_een_gebruiker_te_selectere" +
                        "n_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze gebruiker werd niet teruggevonden in de gegevensbank..
        /// </summary>
        internal static string FrmBeheerder_cmdGebruikerInschrijven_Click_Deze_gebruiker_werd_niet_teruggevonden_in_de_gegevensbank_ {
            get {
                return ResourceManager.GetString("FrmBeheerder_cmdGebruikerInschrijven_Click_Deze_gebruiker_werd_niet_teruggevonden" +
                        "_in_de_gegevensbank_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruiker niet gevonden.
        /// </summary>
        internal static string FrmBeheerder_cmdGebruikerInschrijven_Click_Gebruiker_niet_gevonden {
            get {
                return ResourceManager.GetString("FrmBeheerder_cmdGebruikerInschrijven_Click_Gebruiker_niet_gevonden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De gebruikers uit het CSV-bestand konden niet worden toegevoegd aan de gegevensbank. Probeer het later opnieuw..
        /// </summary>
        internal static string FrmBeheerder_cmdGebruikersToevoegenUitCSV_Click_De_gebruikers_uit_het_CSV_bestand_konden_niet_worden_toegevoegd_aan_de_gegevensbank__Probeer_het_later_opnieuw_ {
            get {
                return ResourceManager.GetString("FrmBeheerder_cmdGebruikersToevoegenUitCSV_Click_De_gebruikers_uit_het_CSV_bestand" +
                        "_konden_niet_worden_toegevoegd_aan_de_gegevensbank__Probeer_het_later_opnieuw_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De gebruiker kon momenteel niet verwijderd worden. Probeer het later opnieuw..
        /// </summary>
        internal static string FrmBeheerder_cmdGebruikerVerwijderen_Click_De_gebruiker_kon_momenteel_niet_verwijderd_worden__Probeer_het_later_opnieuw_ {
            get {
                return ResourceManager.GetString("FrmBeheerder_cmdGebruikerVerwijderen_Click_De_gebruiker_kon_momenteel_niet_verwij" +
                        "derd_worden__Probeer_het_later_opnieuw_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruiker verwijderd..
        /// </summary>
        internal static string FrmBeheerder_cmdGebruikerVerwijderen_Click_Gebruiker_verwijderd_ {
            get {
                return ResourceManager.GetString("FrmBeheerder_cmdGebruikerVerwijderen_Click_Gebruiker_verwijderd_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bent u zeker dat u dit vak wilt verwijderen?.
        /// </summary>
        internal static string FrmBeheerder_cmdVakVerwijderen_Click_Bent_u_zeker_dat_u_dit_vak_wilt_verwijderen_ {
            get {
                return ResourceManager.GetString("FrmBeheerder_cmdVakVerwijderen_Click_Bent_u_zeker_dat_u_dit_vak_wilt_verwijderen_" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het vak is succesvol verwijderd..
        /// </summary>
        internal static string FrmBeheerder_cmdVakVerwijderen_Click_Het_vak_is_succesvol_verwijderd_ {
            get {
                return ResourceManager.GetString("FrmBeheerder_cmdVakVerwijderen_Click_Het_vak_is_succesvol_verwijderd_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het vak kon niet verwijderd worden. Probeer het later opnieuw..
        /// </summary>
        internal static string FrmBeheerder_cmdVakVerwijderen_Click_Het_vak_kon_niet_verwijderd_worden__Probeer_het_later_opnieuw_ {
            get {
                return ResourceManager.GetString("FrmBeheerder_cmdVakVerwijderen_Click_Het_vak_kon_niet_verwijderd_worden__Probeer_" +
                        "het_later_opnieuw_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De mededeling kon niet worden toegevoegd..
        /// </summary>
        internal static string FrmDocent_cmdMededelingToevoegen_Click_De_mededeling_kon_niet_worden_toegevoegd_ {
            get {
                return ResourceManager.GetString("FrmDocent_cmdMededelingToevoegen_Click_De_mededeling_kon_niet_worden_toegevoegd_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De mededeling werd succesvol toegevoegd..
        /// </summary>
        internal static string FrmDocent_cmdMededelingToevoegen_Click_De_mededeling_werd_succesvol_toegevoegd_ {
            get {
                return ResourceManager.GetString("FrmDocent_cmdMededelingToevoegen_Click_De_mededeling_werd_succesvol_toegevoegd_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een beschrijving op te geven die langer is dan 250 tekens..
        /// </summary>
        internal static string FrmDocent_cmdMededelingToevoegen_Click_Gelieve_een_beschrijving_op_te_geven_die_langer_is_dan_250_tekens_ {
            get {
                return ResourceManager.GetString("FrmDocent_cmdMededelingToevoegen_Click_Gelieve_een_beschrijving_op_te_geven_die_l" +
                        "anger_is_dan_250_tekens_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve eerst een vak te selecteren..
        /// </summary>
        internal static string FrmDocent_cmdMededelingToevoegen_Click_Gelieve_eerst_een_vak_te_selecteren_ {
            get {
                return ResourceManager.GetString("FrmDocent_cmdMededelingToevoegen_Click_Gelieve_eerst_een_vak_te_selecteren_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De taak kon niet worden toegevoegd..
        /// </summary>
        internal static string FrmDocent_cmdTakenToevoegen_Click_De_taak_kon_niet_worden_toegevoegd_ {
            get {
                return ResourceManager.GetString("FrmDocent_cmdTakenToevoegen_Click_De_taak_kon_niet_worden_toegevoegd_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De taak werd succesvol toegevoegd..
        /// </summary>
        internal static string FrmDocent_cmdTakenToevoegen_Click_De_taak_werd_succesvol_toegevoegd_ {
            get {
                return ResourceManager.GetString("FrmDocent_cmdTakenToevoegen_Click_De_taak_werd_succesvol_toegevoegd_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De test kon niet worden toegevoegd. Probeer het later opnieuw..
        /// </summary>
        internal static string FrmDocent_cmdTestToevoegen_Click_De_test_kon_niet_worden_toegevoegd__Probeer_het_later_opnieuw_ {
            get {
                return ResourceManager.GetString("FrmDocent_cmdTestToevoegen_Click_De_test_kon_niet_worden_toegevoegd__Probeer_het_" +
                        "later_opnieuw_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De test werd succesvol ingepland..
        /// </summary>
        internal static string FrmDocent_cmdTestToevoegen_Click_De_test_werd_succesvol_ingepland_ {
            get {
                return ResourceManager.GetString("FrmDocent_cmdTestToevoegen_Click_De_test_werd_succesvol_ingepland_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De gebruiker kon niet worden opgeslagen. Probeer het later opnieuw..
        /// </summary>
        internal static string FrmGebruikerAanmaken_cmdOpslagen_Click_De_gebruiker_kon_niet_worden_opgeslagen__Probeer_het_later_opnieuw_ {
            get {
                return ResourceManager.GetString("FrmGebruikerAanmaken_cmdOpslagen_Click_De_gebruiker_kon_niet_worden_opgeslagen__P" +
                        "robeer_het_later_opnieuw_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De gebruiker werd succesvol toegevoegd..
        /// </summary>
        internal static string FrmGebruikerAanmaken_cmdOpslagen_Click_De_gebruiker_werd_succesvol_toegevoegd_ {
            get {
                return ResourceManager.GetString("FrmGebruikerAanmaken_cmdOpslagen_Click_De_gebruiker_werd_succesvol_toegevoegd_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een geboortedatum in het verleden aan te duiden..
        /// </summary>
        internal static string FrmGebruikerAanmaken_cmdOpslagen_Click_Gelieve_een_geboortedatum_in_het_verleden_aan_te_duiden_ {
            get {
                return ResourceManager.GetString("FrmGebruikerAanmaken_cmdOpslagen_Click_Gelieve_een_geboortedatum_in_het_verleden_" +
                        "aan_te_duiden_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een geldig e-mailadres in te vullen (minder dan 60 karakters)..
        /// </summary>
        internal static string FrmGebruikerAanmaken_cmdOpslagen_Click_Gelieve_een_geldig_e_mailadres_in_te_vullen__minder_dan_60_karakters__ {
            get {
                return ResourceManager.GetString("FrmGebruikerAanmaken_cmdOpslagen_Click_Gelieve_een_geldig_e_mailadres_in_te_vulle" +
                        "n__minder_dan_60_karakters__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een geldig wachtwoord in te vullen (minder dan 60 karakters)..
        /// </summary>
        internal static string FrmGebruikerAanmaken_cmdOpslagen_Click_Gelieve_een_geldig_wachtwoord_in_te_vullen__minder_dan_60_karakters__ {
            get {
                return ResourceManager.GetString("FrmGebruikerAanmaken_cmdOpslagen_Click_Gelieve_een_geldig_wachtwoord_in_te_vullen" +
                        "__minder_dan_60_karakters__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een geldige achternaam in te vullen (minder dan 50 karakters)..
        /// </summary>
        internal static string FrmGebruikerAanmaken_cmdOpslagen_Click_Gelieve_een_geldige_achternaam_in_te_vullen__minder_dan_50_karakters__ {
            get {
                return ResourceManager.GetString("FrmGebruikerAanmaken_cmdOpslagen_Click_Gelieve_een_geldige_achternaam_in_te_vulle" +
                        "n__minder_dan_50_karakters__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een geldige voornaam in te vullen (minder dan 50 karakters)..
        /// </summary>
        internal static string FrmGebruikerAanmaken_cmdOpslagen_Click_Gelieve_een_geldige_voornaam_in_te_vullen__minder_dan_50_karakters__ {
            get {
                return ResourceManager.GetString("FrmGebruikerAanmaken_cmdOpslagen_Click_Gelieve_een_geldige_voornaam_in_te_vullen_" +
                        "_minder_dan_50_karakters__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De gebruiker werd succesvol aangepast!.
        /// </summary>
        internal static string FrmGebruikerAanpassen_cmdOpslagen_Click_De_gebruiker_werd_succesvol_aangepast_ {
            get {
                return ResourceManager.GetString("FrmGebruikerAanpassen_cmdOpslagen_Click_De_gebruiker_werd_succesvol_aangepast_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er trad een fout op bij het opslaan van de gebruiker. Probeer het later opnieuw..
        /// </summary>
        internal static string FrmGebruikerAanpassen_cmdOpslagen_Click_Er_trad_een_fout_op_bij_het_opslaan_van_de_gebruiker__Probeer_het_later_opnieuw_ {
            get {
                return ResourceManager.GetString("FrmGebruikerAanpassen_cmdOpslagen_Click_Er_trad_een_fout_op_bij_het_opslaan_van_d" +
                        "e_gebruiker__Probeer_het_later_opnieuw_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De gebruiker kon niet verwijderd worden. Probeer het later opnieuw..
        /// </summary>
        internal static string FrmGebruikerAanpassen_cmdVerwijderen_Click_De_gebruiker_kon_niet_verwijderd_worden__Probeer_het_later_opnieuw_ {
            get {
                return ResourceManager.GetString("FrmGebruikerAanpassen_cmdVerwijderen_Click_De_gebruiker_kon_niet_verwijderd_worde" +
                        "n__Probeer_het_later_opnieuw_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De gebruiker kon niet worden ingeschreven. Probeer het later opnieuw..
        /// </summary>
        internal static string FrmGebruikerInschrijven_cmdInschrijven_Click_De_gebruiker_kon_niet_worden_ingeschreven__Probeer_het_later_opnieuw_ {
            get {
                return ResourceManager.GetString("FrmGebruikerInschrijven_cmdInschrijven_Click_De_gebruiker_kon_niet_worden_ingesch" +
                        "reven__Probeer_het_later_opnieuw_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De gebruiker werd succesvol ingeschreven..
        /// </summary>
        internal static string FrmGebruikerInschrijven_cmdInschrijven_Click_De_gebruiker_werd_succesvol_ingeschreven_ {
            get {
                return ResourceManager.GetString("FrmGebruikerInschrijven_cmdInschrijven_Click_De_gebruiker_werd_succesvol_ingeschr" +
                        "even_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve eerst een rol te selecteren..
        /// </summary>
        internal static string FrmGebruikerInschrijven_cmdInschrijven_Click_Gelieve_eerst_een_rol_te_selecteren_ {
            get {
                return ResourceManager.GetString("FrmGebruikerInschrijven_cmdInschrijven_Click_Gelieve_eerst_een_rol_te_selecteren_" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er kon geen verbinding gemaakt worden met de gegevensbank. Probeer het later opnieuw..
        /// </summary>
        internal static string FrmInloggen_cmdOfficieelInloggen_Click_Er_kon_geen_verbinding_gemaakt_worden_met_de_gegevensbank__Probeer_het_later_opnieuw_ {
            get {
                return ResourceManager.GetString("FrmInloggen_cmdOfficieelInloggen_Click_Er_kon_geen_verbinding_gemaakt_worden_met_" +
                        "de_gegevensbank__Probeer_het_later_opnieuw_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen verbinding.
        /// </summary>
        internal static string FrmInloggen_cmdOfficieelInloggen_Click_Geen_verbinding {
            get {
                return ResourceManager.GetString("FrmInloggen_cmdOfficieelInloggen_Click_Geen_verbinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gegevens onjuist.
        /// </summary>
        internal static string FrmInloggen_cmdOfficieelInloggen_Click_Gegevens_onjuist {
            get {
                return ResourceManager.GetString("FrmInloggen_cmdOfficieelInloggen_Click_Gegevens_onjuist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw gebruikersnaam of wachtwoord is fout. Kijk deze na en probeer het opnieuw..
        /// </summary>
        internal static string FrmInloggen_cmdOfficieelInloggen_Click_Uw_gebruikersnaam_of_wachtwoord_is_fout__Kijk_deze_na_en_probeer_het_opnieuw_ {
            get {
                return ResourceManager.GetString("FrmInloggen_cmdOfficieelInloggen_Click_Uw_gebruikersnaam_of_wachtwoord_is_fout__K" +
                        "ijk_deze_na_en_probeer_het_opnieuw_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De memo kon niet worden opgeslagen. Probeer het later opnieuw..
        /// </summary>
        internal static string FrmStudent_cmdMemoOpslagen_Click_De_memo_kon_niet_worden_opgeslagen__Probeer_het_later_opnieuw_ {
            get {
                return ResourceManager.GetString("FrmStudent_cmdMemoOpslagen_Click_De_memo_kon_niet_worden_opgeslagen__Probeer_het_" +
                        "later_opnieuw_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn geen beschikbare lokalen..
        /// </summary>
        internal static string FrmVakAanpassenAdvanced_cmdLesAanmaken_Click_Er_zijn_geen_beschikbare_lokalen_ {
            get {
                return ResourceManager.GetString("FrmVakAanpassenAdvanced_cmdLesAanmaken_Click_Er_zijn_geen_beschikbare_lokalen_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De les kon niet verwijderd worden. Probeer het later opnieuw..
        /// </summary>
        internal static string FrmVakAanpassenAdvanced_cmdLesVerwijderen_Click_De_les_kon_niet_verwijderd_worden__Probeer_het_later_opnieuw_ {
            get {
                return ResourceManager.GetString("FrmVakAanpassenAdvanced_cmdLesVerwijderen_Click_De_les_kon_niet_verwijderd_worden" +
                        "__Probeer_het_later_opnieuw_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De les werd succesvol verwijderd..
        /// </summary>
        internal static string FrmVakAanpassenAdvanced_cmdLesVerwijderen_Click_De_les_werd_succesvol_verwijderd_ {
            get {
                return ResourceManager.GetString("FrmVakAanpassenAdvanced_cmdLesVerwijderen_Click_De_les_werd_succesvol_verwijderd_" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geboortedatum.
        /// </summary>
        internal static string Geboortedatum {
            get {
                return ResourceManager.GetString("Geboortedatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MetroBack {
            get {
                object obj = ResourceManager.GetObject("MetroBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mislukt.
        /// </summary>
        internal static string Mislukt {
            get {
                return ResourceManager.GetString("Mislukt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er trad een onbekende fout op. Neem aub contact op met Penguin Studio. De applicatie zal zo meteen herstart worden..
        /// </summary>
        internal static string Program_Application_ThreadException_Er_trad_een_onbekende_fout_op__Neem_aub_contact_op_met_Penguin_Studio__De_applicatie_zal_zo_meteen_herstart_worden_ {
            get {
                return ResourceManager.GetString("Program_Application_ThreadException_Er_trad_een_onbekende_fout_op__Neem_aub_conta" +
                        "ct_op_met_Penguin_Studio__De_applicatie_zal_zo_meteen_herstart_worden_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onbekende fout.
        /// </summary>
        internal static string Program_Application_ThreadException_Onbekende_fout {
            get {
                return ResourceManager.GetString("Program_Application_ThreadException_Onbekende_fout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_1rsz_penguin {
            get {
                object obj = ResourceManager.GetObject("rsz_1rsz_penguin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_penguin {
            get {
                object obj = ResourceManager.GetObject("rsz_penguin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string space {
            get {
                return ResourceManager.GetString("space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het aantal studiepunten is geen geldig getal..
        /// </summary>
        internal static string STPParseFout {
            get {
                return ResourceManager.GetString("STPParseFout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De verbinding met de gegevensbank is verbroken. De applicatie zal herstart worden waarna u kan proberen om opnieuw verbinding te maken..
        /// </summary>
        internal static string Utilities_ConnectionLost_De_verbinding_met_de_gegevensbank_is_verbroken__De_applicatie_zal_herstart_worden_waarna_u_kan_proberen_om_opnieuw_verbinding_te_maken_ {
            get {
                return ResourceManager.GetString("Utilities_ConnectionLost_De_verbinding_met_de_gegevensbank_is_verbroken__De_appli" +
                        "catie_zal_herstart_worden_waarna_u_kan_proberen_om_opnieuw_verbinding_te_maken_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbinding verbroken.
        /// </summary>
        internal static string Utilities_ConnectionLost_Verbinding_verbroken {
            get {
                return ResourceManager.GetString("Utilities_ConnectionLost_Verbinding_verbroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vak.
        /// </summary>
        internal static string Vak {
            get {
                return ResourceManager.GetString("Vak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een beschrijving in te vullen voor het vak (max. 50 tekens)..
        /// </summary>
        internal static string VakBeschrijvingInvullen {
            get {
                return ResourceManager.GetString("VakBeschrijvingInvullen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een naam in te vullen voor het vak (max. 50 tekens)..
        /// </summary>
        internal static string VakNaamInvullen {
            get {
                return ResourceManager.GetString("VakNaamInvullen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het vak kon niet worden opgeslagen..
        /// </summary>
        internal static string VakOpslaanMislukt {
            get {
                return ResourceManager.GetString("VakOpslaanMislukt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een aantal studiepunten in te vullen voor het vak..
        /// </summary>
        internal static string VakSTPInvullen {
            get {
                return ResourceManager.GetString("VakSTPInvullen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijderd.
        /// </summary>
        internal static string Verwijderd {
            get {
                return ResourceManager.GetString("Verwijderd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voornaam.
        /// </summary>
        internal static string Voornaam {
            get {
                return ResourceManager.GetString("Voornaam", resourceCulture);
            }
        }
    }
}
